name: using actions

on: push

jobs:
  using-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: ./.github/actions/action
        with:
          who-to-greet: 'Pruthivi'
      - run: ./.github/actions/goodbye
        shell: bash